[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "teresa"
version = "0.1.0"
dependencies = ["click"]

[project.scripts]
teresa = "teresa.cli:coregister"